### ISSUE TITLE
Missing "pr_3_wp.mbn"

### ISSUE THREAD

**Issue by buddyjojo** [Icesito68/7xx-Drivers#3]
[This](https://github.com/Icesito68/7xx-Drivers/commit/718efb3057b8e5100a120cfa66bf579b41417922) commit adds lines in the TrEE driver expecting this firmware file but it was not added to the repo so installation fails with ntstatus 0x80070002.

**Comment by Icesito68** [comment]
Until the last time I tried it worked, but I will try to replace it, Thanks.

**Comment by buddyjojo** [comment]
Thanks, worked fine.
